{% set name = "PyNaCl" %}
{% set version = "1.3.0" %}
{% set sha256 = "0c6100edd16fefd1557da078c7a31e7b7d7a52ce39fdca2bec29d4f7b6e7600c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: "{{ name }}-{{ version }}.tar.gz"
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Remove-average_size-hypothesis-setting-from-test_bin.patch
    - 0002-Fixed-tests-for-change-in-pytest-repr-546.patch
    - 0001-Fix-name-of-static-sodium-lib.patch  # [win]

build:
  number: 1001
  script: 
    - python -m pip install . --no-deps --ignore-installed  # [unix]
  ignore_run_exports:  # [win]
    - libsodium        # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - m2-patch    # [win]
  host:
    - python
    - pip
    - cffi
    - msinttypes  # [win and vc<14]
  run:
    - python
    - six
    - cffi >=1.4.1

test:
  imports:
    - nacl
    - nacl.bindings
    - nacl.pwhash
  requires:
    - pytest
    - pretend
    - hypothesis
  source_files:
    - tests/
  commands:
    - pytest

about:
  home: https://github.com/pyca/pynacl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: PyNaCl is a Python binding to the Networking and Cryptography library, a crypto library with the stated goal of improving usability, security and speed.
  description: |
    PyNaCl is a Python binding to the Networking and Cryptography library, a crypto library with the stated goal of improving usability, security and speed. It supports Python 2.7 and 3.3+ as well as PyPy 2.6+.
  doc_url: https://pynacl.readthedocs.io/en/latest/
  dev_url: https://github.com/pyca/pynacl

extra:
  recipe-maintainers:
    - CJ-Wright
    - mariusvniekerk
