{% set name = "pynacl" %}
{% set version = "1.3.0" %}
{% set sha256 = "205adb2804eed4bc3780584e368ef2e9b8b22a7aae85323068cadd59f3c8a584" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pyca/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [win]
  script: python -m pip install . --no-deps --ignore-installed
  
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cffi
  run:
    - python
    - six
    - cffi

test:
  requires:
    - pytest
    - pretend
    - hypothesis <4
  source_files:
    - tests/
  commands:
    - pytest

about:
  home: https://github.com/pyca/pynacl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: PyNaCl is a Python binding to the Networking and Cryptography library, a crypto library with the stated goal of improving usability, security and speed.
  description: |
    PyNaCl is a Python binding to the Networking and Cryptography library, a crypto library with the stated goal of improving usability, security and speed. It supports Python 2.7 and 3.3+ as well as PyPy 2.6+.
  doc_url: https://pynacl.readthedocs.io/en/latest/
  dev_url: https://github.com/pyca/pynacl

extra:
  recipe-maintainers:
    - CJ-Wright
    - mariusvniekerk
